version: "3"
services:
  backend:
    build: ./python-server
    volumes:
      - ./python-server/:/usr/src/server/python-server
      - ./react-display/:/usr/src/server/react-display
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
